live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
decorations = "buttonless"
startup_mode = "Maximized"
dynamic_padding = false

[window.padding]
x = 10
y = 15

[font]
size = 14.5
offset = { y = 1}

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
