packadd! vim-colors-xcode
packadd! dracula
set termguicolors
syntax on
colorscheme xcodedark

let g:coc_global_extensions = [ 'coc-tsserver', 'coc-prettier', 'coc-eslint', 'coc-metals', 'coc-go' ]
set sts=4

set number
set splitright
set autoindent
set expandtab
set nowrap
let g:go_def_mapping_enabled = 0

let g:ackprg = 'ag --nogroup --nocolor --column'

set wildignore+=*/tmp/*,*.so,*.swp,*.zip

if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

nnoremap <A-Down> :m .+1<CR>==
nnoremap <A-Up> :m .-2<CR>==

noremap <A-f> :set hlsearch! hlsearch?<CR>

nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <C-t> :tabnew<CR>
nnoremap <silent> <A-Left> :tabm -1<CR>
nnoremap <silent> <A-Right> :tabm +1<CR>


nnoremap <C-s> :w<CR>

let g:ctrlp_map = '<c-p>'

" coc-actions
nnoremap <silent> K :call CocAction('doHover')<CR>
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gr <Plug>(coc-references)
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
nmap <silent>ca <Plug>(coc-codeaction)
nmap <leader>rn <Plug>(coc-rename)

" Netrw
" set autochdir
" Toggle Vexplore with Ctrl-E
function! ToggleVExplorer()
  if exists("t:expl_buf_num")
      let expl_win_num = bufwinnr(t:expl_buf_num)
      if expl_win_num != -1
          let cur_win_nr = winnr()
          exec expl_win_num . 'wincmd w'
          close
          exec cur_win_nr . 'wincmd w'
          unlet t:expl_buf_num
      else
          unlet t:expl_buf_num
      endif
  else
      exec '1wincmd w'
      Explore
      let t:expl_buf_num = bufnr("%")
  endif
endfunction
map <silent> <C-b> :call ToggleVExplorer()<CR>


