return {
	enabled = false,
	ls = {
		ltex = {
			cmd = { "ltex-ls" },
			enabled = {
				"bib",
				"gitcommit",
				"markdown",
				"org",
				"plaintex",
				"rst",
				"rnoweb",
				"tex",
				"pandoc",
				"quarto",
				"rmd",
				"context",
				"html",
				"xhtml",
				"mail",
				"text",
			},
			language = "en",
			diagnosticSeverity = "information",
			setenceCacheSize = 2000,
			additionalRules = {
				enablePickyRules = true,
				motherTongue = "en",
			},
			-- trace = { server = "verbose" },
			dictionary = {},
			disabledRules = {},
			hiddenFalsePositives = {},
		},
	},
	deps = {
		"ltex-ls",
	},
}
