--- @meta
-- Canonical plugin spec format (based on lazy.nvim).
-- Plugin files in the plugins dir must return a PluginSpec or PluginSpec[].
--
--- @class PluginSpec
--- @field [1] string Plugin short name ("author/repo")
--- @field enabled? boolean
--- @field lazy? boolean
--- @field dependencies? (string|PluginSpec)[]
--- @field config? fun(plugin: table, opts: table)|true
--- @field opts? table
--- @field init? fun(plugin: table)
--- @field build? string|fun(plugin: table)
--- @field event? string|string[]
--- @field ft? string|string[]
--- @field cmd? string|string[]
--- @field keys? (string|table)[]
--- @field priority? number
